#!/bin/sh
#
# chkconfig: 3 91 05
# description: for ldap-connector
# processname: ldap-connector

name=ldap-connector

. /etc/rc.d/init.d/functions

if [ -f /etc/sysconfig/$name ]; then
        . /etc/sysconfig/$name
fi

user="root"
pidfile="/var/run/ldap-connector/ldap-connector.pid"
lockfile="/var/lock/subsys/$name"
lc_exec="java -XX:-UseGCOverheadLimit -Xmx1024M -Xms1024M -jar ldap-connector.jar --token $TOKEN --sync-interval $INTERVAL --object-classes $OBJCLASS"

start() {
    echo -n $"Starting $name: "
    cd $DIR_EXEC
    daemon --user $user --pidfile ${pidfile} "$lc_exec > /dev/null 2>&1 &"
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && touch $lockfile
    pgrep -f "$lc_exec" > $pidfile
    return $RETVAL
}

stop() {
    echo -n "Stopping $name: "
    killproc -p $pidfile $name
    rm -f $pidfile
    rm -f $lockfile
    echo
}

restart() {
    stop
    start
}

rh_status() {
    status -p $pidfile $name
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


RETVAL=0
case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
       rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    status)
        rh_status
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 2
esac
exit $?

